### ISSUE TITLE
Accidentally added main label in gcc7 build?

### ISSUE THREAD

**Issue by johanneskoester** [conda-forge/r-upsetr-feedstock#4]
Looks like accidentally the main label was added to the gcc7 build:
https://anaconda.org/conda-forge/r-upsetr/files

This has the consequence that the package is pulled into environments where other R packages have been build with a different GCC. I guess this should be fixed by somebody with admin rights in the channel on anaconda.org, or am I missing something here?

@bgruening @dpryan79

**Comment by johanneskoester** [comment]
I might be wrong with the initial assumption. Since the package is noarch, gcc should not matter at all.

**Comment by bgruening** [comment]
That should not matter imho.

**Comment by johanneskoester** [comment]
Ok, I think you are right. See issue #5 for a description of the actual error I see. Something is wrong there.
